### ISSUE TITLE
vulnerability to PROJ6/GDAL3

### ISSUE THREAD

**Issue by rsbivand** [MazamaScience/PWFSLSmoke#104]
Running revdeps from sp (sp (my github fork) with development rgdal from R-Forge):

```
> packageVersion("sp")
[1] ‘1.3.4’
> packageVersion("rgdal")
[1] ‘1.5.3’
> rgdal::rgdal_extSoftVersion()
          GDAL GDAL_with_GEOS           PROJ             sp 
       "3.0.2"         "TRUE"        "6.2.1"        "1.3-2" 
```
a test fails:

```
> test_check("PWFSLSmoke")
  ── 1. Failure: arguments are validated (@test-timeinfo.R#19)  ──────────────────
  `timeInfo <- timeInfo(datetime, longitude, latitude)` produced warnings.
  
  ══ testthat results  ═══════════════════════════════════════════════════════════
  [ OK: 41 | SKIPPED: 2 | WARNINGS: 16 | FAILED: 1 ]
  1. Failure: arguments are validated (@test-timeinfo.R#19) 
```
See:

http://rgdal.r-forge.r-project.org/articles/PROJ6_GDAL3.html
https://github.com/r-spatial/sf/issues/1231
https://github.com/r-spatial/sf/issues/1187
https://github.com/r-spatial/sf/issues/1146
https://github.com/r-spatial/discuss/issues/28

for background. See:

https://github.com/r-spatial/discuss/issues/28#issuecomment-551241421

for a way of testing fixes in a docker container contributed by Jakub Nowosad.

**Comment by rsbivand** [comment]
Problems still present, **rgdal** to be released soon.

**Comment by rsbivand** [comment]
At least test-timeinfo.R line 19:

```
  # Should determine timezone from datetime if no timezone is provided
  expect_silent( timeInfo <- timeInfo(datetime, longitude, latitude) )
```
is broken. Do not use `expect_silent` unless you really control all of the package functions and their external dependencies.

**Comment by jonathancallahan** [comment]
Removed `expect_silent()` as unnecessary and incorrect.

Thanks to rsbivand for the specific suggestion.
