### ISSUE TITLE
Astrid documentation spinup

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/PWFSLSmoke#111]
Before working on documentation, it will be important to get comfortable using various package testing features so that code is only check in when it passes R CMD check.

- [x] Set up Build > More > Configu Build Tools...
- [x] Get comfortable `MazamaCoreUtils::check_fast()` and relatives to check the package at different levels.
- [x] Practice using Build > Test (Cmd-Shift-T). Test scripts are in the `tests/testthat/` directory.
- [x] Practice using Build > Document (Ctrl-Shift-D).
- [x] Practice using Build > Check (Cmd-Shift-E).
- [x] Practice editing roxygen2 comments and viewing result. (Edit comments; Ctrl-Shift-D; open `man/*.Rd` page; Preview)

**Comment by AstridSanna** [comment]
didn't have time to learn more about roxygen2 and we skipped "test".
