### ISSUE TITLE
PM 2.5 Concentration

### ISSUE THREAD

**Issue by nasiegel88** [MazamaScience/PWFSLSmoke#123]
Is there a way to work on PM 2.5 data as a concentration. After looking at the vignettes, I only see a way download AQI data.

**Comment by nasiegel88** [comment]
I see the issue. The EPA website has the air quality listed as concentrations, however, it has not been updated since January of 2018 https://haze.airfire.org/monitoring/EPA/RData/. Do you know when the updated records (for 2018-2021) will be added?

**Comment by jonathancallahan** [comment]
Hi Noah,

We have a Slack workspace set up tow answer questions about this package. I've just invited you to the #pwfsl-smoke channel. Please ask your question again over there and I'll be happy to answer it.

You'll also be able to see other people's questions and answers.

Best,
Jon
