### ISSUE TITLE
refactor monitor_currentData to be more __tidy__

### ISSUE THREAD

**Issue by helenmiller16** [MazamaScience/PWFSLSmoke#25]
`monitor_currentData` currently creates a table with current monitoring data, using some big loops. There are several services that use this function (monitoring-data-ingest and monitor-map), but monitor-presentation uses different logic, relying heavily on tidyr and dplyr functionality. At the very least, the logic should match in all places, but ideally, we would just improve the `monitor_currentData` function to reflect any improvements from using the tidyverse and call it everywhere.

**Comment by spencerpease** [comment]
Function will be renamed to `monitor_getStatus`
