### ISSUE TITLE
create generic_downloadData() and generic_parseData()

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/PWFSLSmoke#50]
These two functions will work in the same as as the other `_downloadData()` and `_parseData()` functions but will allow for the following:

 * `generic_downloadData()` will just accept a URL for now -- use localhost CSV URL for testing
 * `generic_parseData()` will accept a `fileString` and a `configurationList` with all the information needed to properly parse the CSV fileString into a tibble.

`generic_parseData()` should probably be smart enough to handle either a blob of JSON or an R List.

conversion between `configurationList`  `configurationJSON` can be performed with code similar to:

```
    sessionJSON <- jsonlite::toJSON(sessionList, auto_unbox=TRUE, null='null', na='null', pretty=TRUE) # pretty for debugging
```

```
  # Convert JSON to R List
  sessionList <- as.list(jsonlite::fromJSON(sessionJSON,
                                            simplifyVector=TRUE,
                                            simplifyDataFrame=FALSE,
                                            simplifyMatrix=FALSE,
                                            flatten=FALSE))
```

**Comment by spencerpease** [comment]
This is a subset of issue #11
